ChatTile component + Contacts Page
dhwanish-3/Heartless pull request #38
Opened 2024-01-16 14:03 UTC by shellyannissa

Partially done with feature #37 .Added the landing page for Chat section .

2024-01-16 15:13 UTC, dhwanish-3 requested changes
Please
remove avatar
main.dart changes that you did for testing purpose

2024-01-16 18:18 UTC, shellyannissa commented
Have made the requested changes. The frontend is done apart from minor changes such as mechanism to add new member for chatting, chatting with images etc...

2024-01-17 05:34 UTC, dhwanish-3 requested changes

2024-01-17 05:34 UTC, dhwanish-3 commented on lib/widgets/chat_tile.dart
maxlines

2024-01-17 05:34 UTC, dhwanish-3 commented on lib/main.dart
remove testing purpose page

2024-01-17 07:38 UTC, dhwanish-3 commented
Please rebase to main

2024-01-17 18:44 UTC, dhwanish-3 approved these changes
alrighty

2024-01-17 18:44 UTC, merged